Support query words_limit
meilisearch/milli pull request #160
Opened 2021-04-15 08:43 UTC by shekhirin

2021-04-15 14:43 UTC, Kerollmops commented
Hey @shekhirin, are you sure that you need https://github.com/meilisearch/Tokenizer/pull/43 to be able to implement this feature by following @LegendreM's [comment](https://github.com/meilisearch/milli/issues/147#issuecomment-820289885)?

2021-04-15 17:39 UTC, shekhirin commented
@Kerollmops yeah, no need to change Tokenizer for that kind of solving the problem. I made an implementation of that idea in the latest commit.

Still not sure about constant limit of 10 words. Shouldn't be better to pass it from somewhere higher or even make it configurable?

2021-04-19 16:23 UTC, LegendreM requested changes

2021-04-19 16:23 UTC, LegendreM commented on milli/src/search/query_tree.rs
> +    while let (Some(token), true) = (peekable.next(), primitive_query.len() < parts_limit) {
```suggestion
    while let Some(token) = peekable.next() {
        // early return if word limit is exceded
        if primitive_query.len() >= parts_limit { return primitive_query }
```
I find it clearer and allow you to rollback Line 526 🙂

2021-04-19 16:23 UTC, LegendreM commented on milli/src/search/query_tree.rs
> +    if !phrase.is_empty() && primitive_query.len() < parts_limit {
```suggestion
    if !phrase.is_empty() {
```

2021-04-19 16:23 UTC, LegendreM commented on milli/src/search/mod.rs
> +        }
```suggestion
        },
```
We chose to keep the coma on every match cases

2021-04-19 16:23 UTC, LegendreM commented on milli/src/search/mod.rs
> +        })
```suggestion
        Ok(SearchResult { matching_words, candidates: initial_candidates, documents_ids })
```

2021-04-19 16:23 UTC, LegendreM commented on milli/src/search/mod.rs
> +            }
```suggestion
            },
```
We chose to keep the coma on every match cases

2021-04-21 09:04 UTC, LegendreM approved these changes
Good for me!

Thank you @shekhirin for your contribution!

2021-04-21 09:14 UTC, Kerollmops commented
Thank you again @shekhirin 🎉🌮

2021-04-21 09:14 UTC, merged