optimize roaring codec
meilisearch/milli pull request #169
Opened 2021-04-27 12:25 UTC by MarinPostma

Optimize the `BoRoaringBitmapCodec` by preventing it from emiting useless error that caused allocation. On my flamegraph, the byte_decode function went from 4.13% to  1.70%.

This may not be the greatest optimization ever, but hey, this was a low hanging fruit.

2021-04-27 14:58 UTC, Kerollmops requested changes
Thank you for the change :)

2021-04-27 14:58 UTC, Kerollmops commented on milli/src/heed_codec/roaring_bitmap/bo_roaring_bitmap_codec.rs
> +            let integer = bytes.read_u32::<NativeEndian>().ok()?;
Wouldn't it be possible to use bytemuck here? Something like `bytemuck::try_cast_slice(bytes)` followed by a `slice.iter().copied().collect()` as [`RoaringBitmap` impl `FromIterator`](https://docs.rs/roaring/0.6.6/roaring/bitmap/struct.RoaringBitmap.html#impl-FromIterator%3Cu32%3E) ?

2021-04-28 17:10 UTC, Kerollmops requested changes
Thank you for the changes but why is the commit referring to `bytemuck`.

2021-04-28 17:10 UTC, Kerollmops commented on milli/src/heed_codec/roaring_bitmap/bo_roaring_bitmap_codec.rs
> +            .for_each(|bytes| out.extend(&bytes));
```suggestion
            .for_each(|bytes| out.extend_from_slice(&bytes));
```

2021-04-28 18:22 UTC, MarinPostma commented
wow no sorrry, tried many things and forgot about the commit message

2021-04-28 19:02 UTC, Kerollmops requested changes
I am not quite sure why you use a for loop and in another file a `for_each`, could you please use a for loop instead?

2021-04-28 20:13 UTC, MarinPostma commented
well I use a for loop because I don't have a choice, since the conversion is fallible, and I need to propagate the error. In the other case, the conversion can't fail, therefore the for_each can be used.

2021-04-29 08:56 UTC, Kerollmops requested changes
Could you please rebase (we need bors), and I will be able to merge!

2021-05-25 09:34 UTC, Kerollmops requested changes
Could you please rebase, this way I will be able to use bors to merge :)

2021-06-01 06:30 UTC, Kerollmops approved these changes
bors merge

2021-06-01 06:34 UTC, merged