Remove excluded document in criteria iterations
meilisearch/milli pull request #173
Opened 2021-04-28 16:07 UTC by LegendreM

- pass excluded document to criteria to remove them in higher levels of the bucket-sort
- merge already returned document with excluded documents to avoid duplicas

Related to #125 and #112
Fix #170

2021-04-28 17:07 UTC, Kerollmops requested changes
Thank you, I will merge that tomorrow!

2021-04-28 20:24 UTC, MarinPostma commented
Maybe I'm missing something, but aren't candidates passed from a criterion to the next? If it's the case, isn't it necessary to  exclude the documents only on the first criterion in the chain?

2021-04-29 08:36 UTC, LegendreM commented
@MarinPostma we could do as you say. But doing it at each call of next avoid each criterion to fetch and return already distinct documents.

2021-04-29 09:41 UTC, Kerollmops requested changes

2021-04-29 09:41 UTC, Kerollmops commented on milli/src/search/criteria/final.rs
> +                            bucket_candidates.union_with(&candidates);
```suggestion
                            bucket_candidates |= &candidates;
```

2021-04-29 09:41 UTC, Kerollmops commented on milli/src/search/criteria/final.rs
> +                    self.returned_candidates.union_with(&candidates);
```suggestion
                    self.returned_candidates |= &candidates;
```

2021-04-29 09:41 UTC, Kerollmops commented on milli/src/search/criteria/typo.rs
> +                            self.candidates = candidates.map_or_else(|| Candidates::Forbidden(params.excluded_candidates.clone()), Candidates::Allowed);
```suggestion
                            self.candidates = candidates.map_or_else(|| {
                                Candidates::Forbidden(params.excluded_candidates.clone())
                            }, Candidates::Allowed);
```

2021-04-29 10:10 UTC, Kerollmops approved these changes
Thank you, merging!

2021-04-29 10:14 UTC, merged