Transfer numbers and strings facets into the appropriate facet databases
meilisearch/milli pull request #184
Opened 2021-05-03 13:59 UTC by Kerollmops

2021-05-25 09:31 UTC, Kerollmops commented
bors try

2021-05-31 13:16 UTC, LegendreM requested changes

2021-05-31 13:16 UTC, LegendreM commented on milli/src/update/index_documents/store.rs
>                  // TODO must be normalized and not only lowercased.
```suggestion
```

2021-05-31 13:16 UTC, LegendreM commented on milli/src/update/facets.rs
> +            // Store the
```suggestion
```

2021-05-31 13:16 UTC, LegendreM commented on milli/src/search/facet/facet_condition.rs
> +        // TODO we must normalize instead of lowercase.
```suggestion
```

2021-05-31 13:23 UTC, Kerollmops commented
bors try

2021-05-31 13:32 UTC, LegendreM approved these changes

2021-05-31 13:32 UTC, Kerollmops commented
bors merge

2021-05-31 13:36 UTC, merged