Make bucket candidates optionals
meilisearch/milli pull request #190
Opened 2021-05-05 18:48 UTC by LegendreM

2021-05-10 08:14 UTC, Kerollmops requested changes

2021-05-10 08:29 UTC, LegendreM commented on milli/src/search/criteria/initial.rs
> +            bucket_candidates: candidates.take(),
Yes it is

2021-05-10 20:40 UTC, Kerollmops requested changes
Have you tried this PR on the songs dataset?

2021-05-10 20:40 UTC, Kerollmops commented on milli/src/search/criteria/asc_desc.rs
> +                                    resolve_query_tree(&context, qt, params.wdcache)? & &self.faceted_candidates
```suggestion
                                    let candidates = resolve_query_tree(&context, qt, params.wdcache)?;
                                    candidates & &self.faceted_candidates
```

2021-05-10 20:40 UTC, Kerollmops commented on milli/src/search/criteria/attribute.rs
> +type FlattenedQueryTree = Vec<Vec<Vec<Query>>>;
```suggestion
type FlattenedQueryTree = Vec<Vec<Vec<Query>>>;

```

2021-05-10 20:40 UTC, Kerollmops commented on milli/src/search/criteria/final.rs
> +            None => return Ok(None),
```suggestion
                Ok(Some(FinalResult { query_tree, candidates, bucket_candidates }));
            },
            None => Ok(None),
```

2021-05-10 20:40 UTC, Kerollmops commented on milli/src/search/criteria/initial.rs
> +            filtered_candidates: filtered_candidates,
```suggestion
            filtered_candidates,
```

2021-05-10 20:40 UTC, Kerollmops commented on milli/src/search/criteria/mod.rs
> +    /// The candidates, comming from facet filters, that this criterion is allowed to return subsets of.
```suggestion
    /// The candidates, coming from filters, that this criterion is allowed to return subsets of.
```

2021-05-24 11:19 UTC, Kerollmops approved these changes
bors merge

2021-05-24 11:23 UTC, merged