Improve the ci
meilisearch/milli pull request #246
Opened 2021-06-22 09:25 UTC by irevoire

Rewrite entirely the CI:
- run the ci on Linux, macOS and Windows.
- add rustfmt to the CI.
- split the CI into multiple tasks, this way the ci should be faster to fail

2021-06-22 17:01 UTC, curquiza submitted a review, later dismissed
You need to update bors.toml 🙂

2021-06-23 09:27 UTC, Kerollmops approved these changes
Thank you @irevoire!
bors merge

2021-06-23 10:30 UTC, irevoire commented
I'm not sure I understand the problem. Is this like a conflict between bors from the main branch and bors from this branch?

2021-06-23 10:36 UTC, Kerollmops commented
This is bors complaining about the review from curqui, I dismissed here review and trigger a merge  again :)

bors merge

2021-06-23 11:54 UTC, Kerollmops requested changes

2021-06-23 11:54 UTC, Kerollmops commented on bors.toml
> +    'Run Rustfmt',
```suggestion
    'Tests on ubuntu-18.04 with stable',
    'Tests on macos-latest with stable',
    'Cargo check on Windows',
    'Run Rustfmt',
```

In fact I would prefer not to check beta and nightly builds :)

2021-06-23 12:32 UTC, Kerollmops approved these changes
Thank you!
bors merge

2021-06-23 12:45 UTC, curquiza approved these changes

2021-06-23 13:09 UTC, merged