Add benchmarks for the geosearch
meilisearch/milli pull request #357
Opened 2021-09-13 16:18 UTC by irevoire

closes #336

Should I merge this PR in #322 and then we merge everything in `main` or should we wait for #322 to be merged and then merge this one in `main` later?

2021-09-13 16:23 UTC, irevoire commented
Oops I forgot to update the README and the `bench.yaml`. I'm putting this in draft PR for now sorry

2021-09-15 14:33 UTC, curquiza requested changes

2021-09-15 14:33 UTC, curquiza commented on benchmarks/README.md
> +To run only the `search songs` (~1h), `search_wiki` (~3h), `search_geo` (~20m) or `indexing` (~2h) benchmark:
```suggestion
To run only the `search_songs` (~1h), `search_wiki` (~3h), `search_geo` (~20m) or `indexing` (~2h) benchmark:
```

2021-09-15 14:33 UTC, curquiza commented on benchmarks/README.md
> +_[Download the `smol-wiki` dataset](https://milli-benchmarks.fra1.digitaloceanspaces.com/datasets/smol-wiki.csv.gz)._
```suggestion
_[Download the `smol-wiki` dataset](https://milli-benchmarks.fra1.digitaloceanspaces.com/datasets/smol-wiki-articles.csv.gz)._
```

2021-09-15 14:33 UTC, curquiza commented on benchmarks/README.md
> +`smol-all-countries` is a subset of the [`all-countries.csv` dataset]()
```suggestion
`smol-all-countries` is a subset of the [`all-countries.csv` dataset](https://milli-benchmarks.fra1.digitaloceanspaces.com/datasets/all-countries.csv.gz)
```

2021-09-20 12:34 UTC, curquiza approved these changes
Thank you Tamo!!

2021-09-20 12:40 UTC, irevoire commented
@Kerollmops, should I merge this in the #322, or should we first merge the geosearch and then the benchmarks on main? What do you prefer?

2021-09-20 13:06 UTC, Kerollmops commented
I prefer that we merge #322 and this one after :)

2021-09-20 23:09 UTC, irevoire commented
Ok so I guess we can merge now :grin:

2021-09-21 08:28 UTC, Kerollmops approved these changes
Thank you!
Have you tested it with the CI, already?

2021-09-21 08:42 UTC, irevoire commented
Yes!
But now I'm wondering, maybe we could add a geosearch on a really small dataset? ~10.000 documents

2021-09-21 08:47 UTC, Kerollmops commented
How much time does it take to run this one? If it is much longer than the other ones, maybe we should indeed!

2021-09-21 09:11 UTC, irevoire commented
No, currently, all the bench related to the geosearch are super fast. It takes 20 minutes for the search and an insignificant amount of time in the indexing benchmark (1h50m5s before the geosearch vs 1h50m6s with this branch).

So I think it would be good to keep this dataset of 1M documents because it's what we want to improve.
But at the same time, add a really small dataset to ensure we don't lose any performance on small datasets.

2021-09-21 16:07 UTC, Kerollmops approved these changes
You can open a new PR to add a small dataset if you want, I prefer to merge this one for now :)
bors merge

2021-09-21 16:19 UTC, merged