Rewrite the filter parser and add a lot of tests
meilisearch/milli pull request #400
Opened 2021-10-20 15:36 UTC by irevoire

This PR is a complete rewrite of #358, which was reverted in #403.
You can already try this PR in Meilisearch here https://github.com/meilisearch/MeiliSearch/pull/1880.

Since writing a parser is quite complicated, I moved all the logic to another workspace called `filter_parser`.
In this workspace, we don't know anything about milli, the filterable fields / field ID or anything.
As you can see in its `cargo.toml`, it has only three dependencies entirely focused on the parsing part:
```
nom = "7.0.0"
nom_locate = "4.0.0"
```

But introducing this new workspace made some changes necessary on the “AST”. Now the parser only returns `Tokens` (a simple `&str` with a bit of context). Everything is interpreted when we execute the filter later in milli.
This crate provides a new error type for all filter related errors.

---------
## Errors

Currently, we have multiple kinds of errors. Sometimes we are generating errors looking like that: (for `name = truc`)
```
Attribute `name` is not filterable. Available filterable attributes are: ``.
```
While sometimes pest was generating errors looking like that:
```
Invalid syntax for the filter parameter: ` --> 1:7
  |
1 | name =
  |       ^---
  |
  = expected word`.
```

Which most people were seeing like that: (for `name =`)
```
Invalid syntax for the filter parameter: ` --> 1:7\n  |\n1 | name =\n  |       ^---\n  |\n  = expected word`.
```

-----------

With this PR, the error format is unified between all errors.
All errors follow this more straightforward format:
```
The error message.
[from char]:[to char] filter
```

This should be way easier to read when embedded in the JSON for a human. And it should also allow us to parse the errors easily and provide highlighting or something with a frontend playground.

Here is an example of the two previous errors with the new format:
For `name = truc`:
```
Attribute `name` is not filterable. Available filterable attributes are: ``.
1:4 name = truc
```
Or in one line:
```
Attribute `name` is not filterable. Available filterable attributes are: ``.\n1:4 name = truc
```

And for `name =`:
```
Was expecting a value but instead got nothing.
7:7 name =
```
Or in one line:
```
Was expecting a value but instead got nothing.\n7:7 name =
```

Also, since we now have control over the parser, we can generate more explicit error messages so a lot of new errors have been created. I tried to be as helpful as possible for the user; here is a little overview of the new error message you can get when misusing a filter:
```
Expression `"truc` is missing the following closing delimiter: `"`.
8:13 name = "truc
```
The `_geoRadius` filter is an operation and can't be used as a value.
8:30 name = _geoRadius(12, 13, 14)
```
etc

## Tests
A lot of tests have been written in the `filter_parser` crate. I think there is a unit test for every part of the syntax. 
But since we can never be sure we covered all the cases, I also fuzzed the new parser A LOT (for ±8 hours on 20 threads). And the code to fuzz the parser is included in the workspace, so if one day we need to change something to the syntax, we'll be able to re-use it by simply running:
```
cargo fuzz run --release parse
```

## Milli
I renamed the type and module `filter_condition.rs` / `FilterCondition` to `filter.rs` / `Filter`.

2021-11-08 17:58 UTC, MarinPostma requested changes

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/condition.rs
> +    let (input, (key, op, value)) = tuple((|c| parse_value(c), operator, cut(parse_value)))(input)?;
```suggestion
    let (input, (fid, op, value)) = tuple((parse_value, operator, cut(parse_value)))(input)?;
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/condition.rs
> +    let fid = key;
```suggestion
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/condition.rs
> +    }
can you flatten that?

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/condition.rs
> +        tuple((|c| parse_value(c), |c| parse_value(c), tag("TO"), cut(parse_value)))(input)?;
```suggestion
        tuple((parse_value, parse_value, tag("TO"), cut(parse_value)))(input)?;
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/error.rs
> +pub trait ExtendNomError<E> {
```suggestion
pub trait NomErrorExt<E> {
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/lib.rs
> +//! doubleQuoted   = "\"" (word | spaces)* "\""
```suggestion
//! singleQuoted   = "'" .* all but quotes "'"
//! doubleQuoted   = "\"" .* all but double quotes "\""
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/lib.rs
> +//! geoRadius      = WS* ~ "_geoRadius(" ~ float ~ "," ~ float ~ "," float ~ ")"
add whitespaces?

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/lib.rs
> +}
```suggestion
#[derive(Debug, Clone, Eq)]
pub struct Token<'a>(Span<'a>)
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/lib.rs
> +        cut(delimited(char('('), separated_list1(tag(","), ws(|c| recognize_float(c))), char(')'))),
```suggestion
        cut(delimited(char('('), separated_list1(tag(","), ws(recognize_float)), char(')'))),
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/lib.rs
> +        |c| parse_geo_point(c),
```suggestion
        parse_geo_radius,
        parse_condition,
        parse_to,
        // the next lines are only for error handling and are written at the end to have the less possible performance impact
        parse_geo_point,
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/value.rs
> +    let err = parse_geo_point(input).unwrap_err();
It will panic if you pass it a geopoint

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/value.rs
> +    let double_quoted = |input| take_till(|c: char| c == '"')(input);
```suggestion
    let simple_quoted = take_till(|c: char| c == '\'');
    // doubleQuoted   = "\"" (word | spaces)* "\""
    let double_quoted = take_till(|c: char| c == '"');
```

2021-11-08 17:58 UTC, MarinPostma commented on filter_parser/src/value.rs
> +fn is_key_component(c: char) -> bool {
```suggestion
fn is_value_component(c: char) -> bool {
```

2021-11-09 10:35 UTC, MarinPostma approved these changes
Great work! thank you @irevoire !

2021-11-09 13:24 UTC, Kerollmops requested changes

2021-11-09 13:24 UTC, Kerollmops commented on filter_parser/src/lib.rs
> +//! not            = ("NOT" | "!") not | primary
Could you please remove `!` from the syntax it was not in it in the previous parser.

2021-11-09 13:24 UTC, Kerollmops commented on filter_parser/src/lib.rs
> +        // if we were able to parse `_geoRadius` and can't parse the rest of the input we returns a failure
```suggestion
        // if we were able to parse `_geoRadius` and can't parse the rest of the input we return a failure
```

2021-11-09 13:24 UTC, Kerollmops commented on filter_parser/src/lib.rs
> +    // if we succeeded we still returns a Failure because geoPoints are not allowed
```suggestion
    // if we succeeded we still return a Failure because geoPoints are not allowed
```

2021-11-09 13:24 UTC, Kerollmops commented on filter_parser/src/value.rs
> +    c.is_whitespace() || ['(', ')', '=', '<', '>', '!'].contains(&c)
```suggestion
    c.is_whitespace() || ['(', ')', '=', '<', '>'].contains(&c)
```

2021-11-09 15:37 UTC, irevoire commented on filter_parser/fuzz/.gitignore
> +target
It’s because the fuzz directory is not in any workspace.

2021-11-09 15:37 UTC, irevoire commented on filter_parser/src/error.rs
> +    MisusedGeo,
Yes I think that’s the case: https://dictionary.cambridge.org/dictionary/english/misused

2021-11-09 15:39 UTC, Kerollmops reviewed
Did you just delete all the `filter_parser/fuzz/corpus/parse/test_*` files?

2021-11-09 15:42 UTC, irevoire commented
> Did you just delete all the `filter_parser/fuzz/corpus/parse/test_*` files?

Oops yes sorry, when I renamed my directory git did not add these files back since they are ignored by default 😁

2021-11-09 15:57 UTC, Kerollmops requested changes
That's a sacré PR that I see!

We will finally be able to close this PR! GG!
https://github.com/meilisearch/MeiliSearch/issues/837

2021-11-09 15:57 UTC, Kerollmops commented on filter-parser/src/condition.rs
> +        ">=" => FilterCondition::Condition { fid, op: GreaterThanOrEqual(value) },
```suggestion
        "<=" => FilterCondition::Condition { fid, op: LowerThanOrEqual(value) },
        ">=" => FilterCondition::Condition { fid, op: GreaterThanOrEqual(value) },
        "!=" => FilterCondition::Condition { fid, op: NotEqual(value) },
        "<" => FilterCondition::Condition { fid, op: LowerThan(value) },
        ">" => FilterCondition::Condition { fid, op: GreaterThan(value) },
        "=" => FilterCondition::Condition { fid, op: Equal(value) },
```

2021-11-09 15:57 UTC, Kerollmops commented on milli/Cargo.toml
> +filter-parser = { path = "../filter-parser" }
❤️

2021-11-09 16:09 UTC, Kerollmops approved these changes
Thank you @irevoire ! 🎉

2021-11-09 16:09 UTC, irevoire commented
bors merge

2021-11-09 16:40 UTC, merged