Fix search highlight for non-unicode chars
meilisearch/milli pull request #426
Opened 2021-12-17 17:35 UTC by Samyak2

# Pull Request

## What does this PR do?
Fixes https://github.com/meilisearch/MeiliSearch/issues/1480

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

## Changes

The `matching_bytes` function takes a `&Token` now and:
- gets the number of bytes to highlight (unchanged).
- uses `Token.num_graphemes_from_bytes` to get the number of grapheme clusters to highlight.

In essence, the `matching_bytes` function now returns the number of matching grapheme clusters instead of bytes.

Added proper highlighting in the HTTP UI:
- requires dependency on `unicode-segmentation` to extract grapheme clusters from tokens
- `<mark>` tag is put around only the matched part
    - before this change, the entire word was highlighted even if only a part of it matched

## Questions

Since `matching_bytes` does not return number of bytes but grapheme clusters, should it be renamed to something like `matching_chars` or `matching_graphemes`? Will this break the API?

Thank you very much @ManyTheFish for helping :smile:

2021-12-17 17:37 UTC, Samyak2 commented
Ah I just found out that the tests for `milli` fail. Will fix in some time.

2021-12-17 17:59 UTC, Samyak2 commented
I have fixed the tests to build successfully, but they still fail. I think it's due a mistake I made in https://github.com/meilisearch/tokenizer/pull/59/files#diff-76ada62566331039fde44902c7d08ec1f2c977a147cdefcefc466e07cedafc4fR89

It should be:
```rust
            None => num_bytes,
```

2021-12-17 18:10 UTC, Samyak2 commented
Opened a PR there: https://github.com/meilisearch/tokenizer/pull/64

Sorry about this :grimacing:

2021-12-20 09:09 UTC, curquiza commented
Thanks @Samyak2 for your work 😄 

@ManyTheFish @Kerollmops https://github.com/meilisearch/tokenizer/pull/64 should be reviewed (and merged if accepted) before merging this PR

2021-12-22 14:01 UTC, ManyTheFish requested changes

2022-01-15 10:44 UTC, Samyak2 commented
Just noticed that Tokenizer v0.2.7 was released with my fix! I'll update this PR soon. Thanks for your patience :smile:

2022-01-17 07:46 UTC, Samyak2 commented on http-ui/src/main.rs
> +                            string.push_str(word);
Done in c0313f3

2022-01-17 07:51 UTC, Samyak2 commented
The highlighting works well now! Screenshots:

![Spectacle_last](https://user-images.githubusercontent.com/34161949/149728373-8cdc6794-67ad-44d8-9eb8-adbec743e603.png)

![Spectacle_last](https://user-images.githubusercontent.com/34161949/149728405-23379f00-9aef-4816-8f90-d01740ac5148.png)

![Spectacle_last](https://user-images.githubusercontent.com/34161949/149728497-88d8b97f-fd1e-44d7-a8bb-e84e9605c27c.png)

---

But, there is an issue if only a part of `briefcase` matches. For example, `gobrifcaseod` does not highlight the last `d` since only the first 12 chars match. `gobrifcaseood` matches the whole word though.

I think it's a minor issues and it works quite well even with it.

![Spectacle_last](https://user-images.githubusercontent.com/34161949/149728736-c6065c98-01c8-42c1-99b6-905960379dd6.png)

2022-01-17 13:38 UTC, ManyTheFish commented
Hello @Samyak2, I agree with you, despite this minor issue It's a big improvement, thanks a lot for your work!

Bors merge

2022-01-17 13:40 UTC, ManyTheFish approved these changes

2022-01-17 13:45 UTC, Samyak2 commented
Thank you for guiding me through all of my PRs :heart:

2022-01-17 13:51 UTC, merged