Disable typos on exact word
meilisearch/milli pull request #474
Opened 2022-03-21 15:31 UTC by MarinPostma

This PR introduces the `exact_word` setting to disable typo tolerance on custom words.

If a user query contains a word from `exact_words`, no typo derivation will be made for that particular word.

2022-04-04 18:27 UTC, Kerollmops requested changes

2022-04-04 18:27 UTC, Kerollmops commented on milli/src/search/query_tree.rs
> +                    TypoConfig { max_typos: 2, word_len_one_typo, word_len_two_typo, exact_words };
```suggestion
                let config =
                    TypoConfig { max_typos: 2, word_len_one_typo, word_len_two_typo, exact_words: ctx.exact_words()? };
```

2022-04-04 18:27 UTC, Kerollmops commented on milli/src/search/query_tree.rs
> +                            };
```suggestion
                            let config = TypoConfig {
                                max_typos: 1,
                                word_len_one_typo,
                                word_len_two_typo,
                                exact_words: ctx.exact_words()?,
                            };
```

2022-04-04 18:27 UTC, Kerollmops commented on milli/tests/search/typo_tolerance.rs
> +    // sealand doesn't allow typos anymore
```suggestion
    // zearand doesn't allow typos anymore
```

2022-04-04 18:32 UTC, MarinPostma commented on milli/src/search/query_tree.rs
> +                    TypoConfig { max_typos: 2, word_len_one_typo, word_len_two_typo, exact_words };
fmt doesn't allow that

2022-04-04 18:33 UTC, MarinPostma commented on milli/src/search/query_tree.rs
> +                            };
fmt doesn't allow that

2022-04-04 18:34 UTC, MarinPostma commented on milli/tests/search/typo_tolerance.rs
> +    // sealand doesn't allow typos anymore
```suggestion
    // `zealand` doesn't allow typos anymore
```

2022-04-04 18:36 UTC, Kerollmops approved these changes
Thank you very much! Ready to be merged :)

2022-04-04 18:39 UTC, MarinPostma commented
bors merge

2022-04-04 18:51 UTC, merged

2022-05-23 15:18 UTC, Kerollmops commented on milli/src/index.rs
> +    }
We MUST return an optional `fst::Set` from this function and never call this default method when executing queries. We should investigate the fact that it is or not the reason for the performance issue!