Bump tokenizer
meilisearch/milli pull request #475
Opened 2022-03-21 16:33 UTC by irevoire

# Pull Request

## What does this PR do?
Fixes #<issue_number>

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-03-22 09:05 UTC, ManyTheFish submitted a review, later dismissed

2022-03-22 13:06 UTC, MarinPostma commented
bors try

2022-03-23 11:21 UTC, Kerollmops requested changes
Could you please change the description of the PR? And we **must** also make sure that we `cargo update` to bump the lock of Meilisearch with lindera _0.12.1_.

2022-03-23 13:24 UTC, Kerollmops submitted a review, later dismissed
bors merge

2022-03-23 13:26 UTC, Kerollmops approved these changes
bors merge

2022-03-23 13:59 UTC, merged