Enhance matching words
meilisearch/milli pull request #483
Opened 2022-03-30 12:49 UTC by ManyTheFish

# Summary

Enhance milli word-matcher making it handle match computing and cropping.

# Implementation

## Computing best matches for cropping

Before we were considering that the first match of the attribute was the best one, this was accurate when only one word was searched but was missing the target when more than one word was searched.

Now we are searching for the best matches interval to crop around, the chosen interval is the one:
1) that have the highest count of unique matches
> for example, if we have a query `split the world`, then the interval `the split the split the` has 5 matches but only 2 unique matches (1 for `split` and 1 for `the`) where the interval `split of the world` has 3 matches and 3 unique matches. So the interval `split of the world` is considered better.
2) that have the minimum distance between matches
> for example, if we have a query `split the world`, then the interval `split of the world` has a distance of 3 (2 between `split` and `the`, and 1 between `the` and `world`) where the interval `split the world` has a distance of 2. So the interval `split the world` is considered better.
3) that have the highest count of ordered matches
> for example, if we have a query `split the world`, then the interval `the world split` has 2 ordered words where the interval `split the world` has 3. So the interval `split the world` is considered better.

## Cropping around the best matches interval

Before we were cropping around the interval without checking the context.

Now we are cropping around words in the same context as matching words.
This means that we will keep words that are farther from the matching words but are in the same phrase, than words that are nearer but separated by a dot.

For instance, for the matching word `Split` the text:
`Natalie risk her future. Split The World is a book written by Emily Henry. I never read it.`
will be cropped like:
`…. Split The World is a book written by Emily Henry. …`
and  not like:
`Natalie risk her future. Split The World is a book …`

2022-04-06 00:10 UTC, Kerollmops reviewed
I am aware that this PR is incomplete and must be benchmarked, especially the essential parts: the `create_matching_words` function and the `matches/mod.rs` module.

The only remark that I want to say is that it seems quite complex, and I have no real idea how to fix that. We should probably delay it and benchmark it before releasing it. There are some parts that could be rewritten with idiomatic code. I know that the algorithm complexity doesn't make that easy to do.

2022-04-06 08:35 UTC, ManyTheFish commented on milli/src/search/matches/mod.rs
> +const DEFAULT_HIGHLIGHT_SUFFIX: &'static str = "</em>";
<em> is the default tag specified by the spec, but, http-ui needs <mark>.

2022-04-07 22:01 UTC, Kerollmops approved these changes
It is much better now, thank you for that!

2022-04-11 17:05 UTC, Kerollmops approved these changes

2022-04-12 08:24 UTC, ManyTheFish commented on http-ui/src/main.rs
> +                Value::String(matcher.format(true, true).to_string())
I can move it into the builder with a specific method for each 🤔

2022-04-12 11:45 UTC, ManyTheFish commented on http-ui/src/main.rs
> +                Value::String(matcher.format(true, true).to_string())
I choose to use [FormatOption](https://github.com/meilisearch/meilisearch/blob/f67167fa9f473c1dba5d9485093a4768fc70a32d/meilisearch-lib/src/index/search.rs#L109-L122) struct coming from Meilisearch which will ease the future integration.

2022-04-14 21:02 UTC, Kerollmops requested changes
This is, indeed, better with this struct, thank you!

2022-04-14 21:02 UTC, Kerollmops commented on milli/src/search/matches/mod.rs
> +        assert_eq!(&matcher.format(format_options.clone()), &text);
Why not implementing `Copy` on this struct?

2022-04-19 11:42 UTC, Kerollmops approved these changes
I like what I see, merging!
bors merge

2022-04-19 12:43 UTC, merged

2022-05-23 15:33 UTC, ManyTheFish commented on milli/src/search/query_tree.rs
> +            Ok(Some((qt, primitive_query, matching_words)))
try to replace `create_matching_word` call by:
```rust
    fn matching_words() -> MatchingWords {
        let matching_words = vec![
            (vec![MatchingWord::new("split".to_string(), 0, false)], vec![0]),
            (vec![MatchingWord::new("the".to_string(), 0, false)], vec![1]),
            (vec![MatchingWord::new("world".to_string(), 1, true)], vec![2]),
        ];

        MatchingWords::new(matching_words)
    }
```

2022-05-23 15:33 UTC, ManyTheFish commented on milli/src/search/query_tree.rs
> +            Ok(Some((qt, primitive_query, matching_words)))
`MatchingWords::new(vec![])`

2022-05-24 09:36 UTC, Kerollmops commented on milli/src/search/query_tree.rs
> +            Ok(Some((qt, primitive_query, matching_words)))
Ok, so you are running the benchmarks from https://github.com/meilisearch/milli/pull/537!

2022-05-24 12:46 UTC, irevoire commented on milli/src/search/query_tree.rs
> +            Ok(Some((qt, primitive_query, matching_words)))
Everything got faster by a good margin; 

<details>
<summary>Your fix against this PR</summary>

```
group                                                                                                    search_songs_improve-bench_3824ee55    search_songs_main_ea4bb940
-----                                                                                                    -----------------------------------    --------------------------
smol-songs.csv: asc + default/Notstandskomitee                                                           1.00      3.5±0.02ms        ? ?/sec    1.03      3.6±0.02ms        ? ?/sec
smol-songs.csv: asc + default/charles                                                                    1.00      2.5±0.01ms        ? ?/sec    1.04      2.5±0.01ms        ? ?/sec
smol-songs.csv: asc + default/charles mingus                                                             1.00      3.6±0.02ms        ? ?/sec    1.08      3.9±0.02ms        ? ?/sec
smol-songs.csv: asc + default/david                                                                      1.00      3.3±0.01ms        ? ?/sec    1.02      3.3±0.04ms        ? ?/sec
smol-songs.csv: asc + default/david bowie                                                                1.00      5.1±0.02ms        ? ?/sec    1.05      5.4±0.02ms        ? ?/sec
smol-songs.csv: asc + default/john                                                                       1.00      3.6±0.01ms        ? ?/sec    1.03      3.7±0.02ms        ? ?/sec
smol-songs.csv: asc + default/marcus miller                                                              1.00      5.6±0.02ms        ? ?/sec    1.04      5.9±0.02ms        ? ?/sec
smol-songs.csv: asc + default/michael jackson                                                            1.00      5.2±0.02ms        ? ?/sec    1.07      5.5±0.02ms        ? ?/sec
smol-songs.csv: asc + default/tamo                                                                       1.00   1636.1±9.22µs        ? ?/sec    1.05  1713.9±11.57µs        ? ?/sec
smol-songs.csv: asc + default/thelonious monk                                                            1.00      5.6±0.02ms        ? ?/sec    1.05      5.9±0.29ms        ? ?/sec
smol-songs.csv: asc/Notstandskomitee                                                                     1.00      3.1±0.01ms        ? ?/sec    1.10      3.4±0.71ms        ? ?/sec
smol-songs.csv: asc/charles                                                                              1.00    577.6±4.37µs        ? ?/sec    1.16    668.3±3.17µs        ? ?/sec
smol-songs.csv: asc/charles mingus                                                                       1.00   1101.9±9.81µs        ? ?/sec    1.28  1408.8±149.50µs        ? ?/sec
smol-songs.csv: asc/david                                                                                1.00    865.5±3.22µs        ? ?/sec    1.11    957.9±5.74µs        ? ?/sec
smol-songs.csv: asc/david bowie                                                                          1.00  1456.6±11.51µs        ? ?/sec    1.19  1739.9±176.35µs        ? ?/sec
smol-songs.csv: asc/john                                                                                 1.00    761.2±3.43µs        ? ?/sec    1.11    845.6±4.98µs        ? ?/sec
smol-songs.csv: asc/marcus miller                                                                        1.00  1356.3±11.01µs        ? ?/sec    1.20  1629.5±111.53µs        ? ?/sec
smol-songs.csv: asc/michael jackson                                                                      1.00   1374.7±7.89µs        ? ?/sec    1.22  1675.3±10.50µs        ? ?/sec
smol-songs.csv: asc/tamo                                                                                 1.00    143.9±1.73µs        ? ?/sec    1.59    228.2±2.47µs        ? ?/sec
smol-songs.csv: asc/thelonious monk                                                                      1.00      3.7±0.02ms        ? ?/sec    1.14      4.2±0.88ms        ? ?/sec
smol-songs.csv: basic filter: <=/Notstandskomitee                                                        1.00    105.8±0.75µs        ? ?/sec    2.69    284.2±2.94µs        ? ?/sec
smol-songs.csv: basic filter: <=/charles                                                                 1.00     97.8±0.98µs        ? ?/sec    2.00    195.8±1.23µs        ? ?/sec
smol-songs.csv: basic filter: <=/charles mingus                                                          1.00    321.4±8.88µs        ? ?/sec    1.89    608.4±6.02µs        ? ?/sec
smol-songs.csv: basic filter: <=/david                                                                   1.00     97.1±1.81µs        ? ?/sec    1.95    189.4±2.81µs        ? ?/sec
smol-songs.csv: basic filter: <=/david bowie                                                             1.00    313.5±8.98µs        ? ?/sec    1.85    579.8±2.84µs        ? ?/sec
smol-songs.csv: basic filter: <=/john                                                                    1.00     97.3±0.55µs        ? ?/sec    1.87    182.0±1.52µs        ? ?/sec
smol-songs.csv: basic filter: <=/marcus miller                                                           1.00    314.8±1.76µs        ? ?/sec    1.90    596.8±3.63µs        ? ?/sec
smol-songs.csv: basic filter: <=/michael jackson                                                         1.00    322.6±9.09µs        ? ?/sec    1.88    608.1±3.91µs        ? ?/sec
smol-songs.csv: basic filter: <=/tamo                                                                    1.00     95.8±0.76µs        ? ?/sec    1.98   190.1±14.42µs        ? ?/sec
smol-songs.csv: basic filter: <=/thelonious monk                                                         1.00    325.1±4.19µs        ? ?/sec    1.96    635.9±3.40µs        ? ?/sec
smol-songs.csv: basic filter: TO/Notstandskomitee                                                        1.00    106.8±1.10µs        ? ?/sec    2.90   309.3±16.35µs        ? ?/sec
smol-songs.csv: basic filter: TO/charles                                                                 1.00     99.1±0.92µs        ? ?/sec    1.99    197.2±6.85µs        ? ?/sec
smol-songs.csv: basic filter: TO/charles mingus                                                          1.00    318.5±9.75µs        ? ?/sec    1.87    597.1±3.11µs        ? ?/sec
smol-songs.csv: basic filter: TO/david                                                                   1.00     97.9±3.72µs        ? ?/sec    1.92    187.5±2.82µs        ? ?/sec
smol-songs.csv: basic filter: TO/david bowie                                                             1.00    315.0±9.05µs        ? ?/sec    1.87  590.6±128.06µs        ? ?/sec
smol-songs.csv: basic filter: TO/john                                                                    1.00     96.9±0.88µs        ? ?/sec    1.87    181.3±1.52µs        ? ?/sec
smol-songs.csv: basic filter: TO/marcus miller                                                           1.00    316.1±8.40µs        ? ?/sec    1.89    596.4±3.81µs        ? ?/sec
smol-songs.csv: basic filter: TO/michael jackson                                                         1.00    323.5±8.45µs        ? ?/sec    1.87    606.3±3.84µs        ? ?/sec
smol-songs.csv: basic filter: TO/tamo                                                                    1.00     95.9±0.62µs        ? ?/sec    1.92    183.9±1.79µs        ? ?/sec
smol-songs.csv: basic filter: TO/thelonious monk                                                         1.00    321.7±8.53µs        ? ?/sec    1.97    632.8±4.33µs        ? ?/sec
smol-songs.csv: basic placeholder/                                                                       1.01     58.9±0.40µs        ? ?/sec    1.00     58.5±0.60µs        ? ?/sec
smol-songs.csv: basic with quote/"Notstandskomitee"                                                      1.00    193.8±1.30µs        ? ?/sec    1.08    209.4±1.60µs        ?  [...]