speedup exact words
meilisearch/milli pull request #538
Opened 2022-05-24 07:48 UTC by MarinPostma

This PR make `exact_words` return an `Option` instead of an empty set, since set creation is costly, as noticed by @kerollmops.

I was not convinces that this was the cause for all of the performance drop we measured, and then realized that methods that initialized it were called recursively which caused initialization times to add up. While the first fix solves the issue when not using exact words, using exact word remained way more expensive that it should be. To address this issue, the exact words are cached into the `Context`, so they are only initialized once.

2022-05-24 09:34 UTC, Kerollmops requested changes

2022-05-24 11:50 UTC, Kerollmops commented on milli/src/index.rs
> +            None => Ok(None),
Ho Ok, you are right, didn't see that!

2022-05-24 11:53 UTC, Kerollmops requested changes

2022-05-24 11:53 UTC, Kerollmops commented on milli/src/search/query_tree.rs
> +    if authorize_typos && !config.exact_words.as_ref().map(|s| s.contains(&word)).unwrap_or(false) {
```suggestion
    if authorize_typos && !config.exact_words.map_or(false, |s| s.contains(&word)) {
```

2022-05-24 11:53 UTC, Kerollmops commented on milli/src/search/query_tree.rs
> +            exact_words,
```suggestion
        Ok(Self {
            rtxn,
            index,
            optional_words: true,
            authorize_typos: true,
            words_limit: None,
            exact_words: index.exact_words(rtxn)?,
```

2022-05-24 16:41 UTC, Kerollmops reviewed
Could you please run the search benchmarks on this branch, please? This way we will see the changes!

2022-05-30 07:46 UTC, MarinPostma commented
```
group                                                                                                    search_songs_main_9f78e392             search_songs_speedup-exact-words_25fc5766
-----                                                                                                    --------------------------             -----------------------------------------
smol-songs.csv: asc + default/Notstandskomitee                                                           1.01      3.6±0.02ms        ? ?/sec    1.00      3.6±0.03ms        ? ?/sec
smol-songs.csv: asc + default/charles                                                                    1.05      2.5±0.01ms        ? ?/sec    1.00      2.4±0.01ms        ? ?/sec
smol-songs.csv: asc + default/charles mingus                                                             1.18      4.0±0.02ms        ? ?/sec    1.00      3.4±0.01ms        ? ?/sec
smol-songs.csv: asc + default/david                                                                      1.04      3.4±0.01ms        ? ?/sec    1.00      3.2±0.01ms        ? ?/sec
smol-songs.csv: asc + default/david bowie                                                                1.11      5.5±0.02ms        ? ?/sec    1.00      4.9±0.02ms        ? ?/sec
smol-songs.csv: asc + default/john                                                                       1.04      3.7±0.01ms        ? ?/sec    1.00      3.5±0.02ms        ? ?/sec
smol-songs.csv: asc + default/marcus miller                                                              1.12      6.1±0.02ms        ? ?/sec    1.00      5.5±0.03ms        ? ?/sec
smol-songs.csv: asc + default/michael jackson                                                            1.11      5.5±0.02ms        ? ?/sec    1.00      5.0±0.02ms        ? ?/sec
smol-songs.csv: asc + default/tamo                                                                       1.10  1706.7±15.65µs        ? ?/sec    1.00  1552.0±11.03µs        ? ?/sec
smol-songs.csv: asc + default/thelonious monk                                                            1.08      5.7±0.02ms        ? ?/sec    1.00      5.3±0.02ms        ? ?/sec
smol-songs.csv: asc/Notstandskomitee                                                                     1.02      3.3±0.02ms        ? ?/sec    1.00      3.2±0.01ms        ? ?/sec
smol-songs.csv: asc/charles                                                                              1.28    678.5±3.86µs        ? ?/sec    1.00   530.2±12.36µs        ? ?/sec
smol-songs.csv: asc/charles mingus                                                                       1.56  1409.0±40.88µs        ? ?/sec    1.00    903.5±4.18µs        ? ?/sec
smol-songs.csv: asc/david                                                                                1.18    963.3±4.31µs        ? ?/sec    1.00    816.2±8.37µs        ? ?/sec
smol-songs.csv: asc/david bowie                                                                          1.39  1722.6±39.79µs        ? ?/sec    1.00   1238.6±8.40µs        ? ?/sec
smol-songs.csv: asc/john                                                                                 1.20    849.6±3.28µs        ? ?/sec    1.00    707.9±5.37µs        ? ?/sec
smol-songs.csv: asc/marcus miller                                                                        1.43   1635.8±8.91µs        ? ?/sec    1.00  1142.0±17.96µs        ? ?/sec
smol-songs.csv: asc/michael jackson                                                                      1.41  1684.4±18.05µs        ? ?/sec    1.00  1192.5±12.75µs        ? ?/sec
smol-songs.csv: asc/tamo                                                                                 2.73    231.0±1.57µs        ? ?/sec    1.00     84.5±0.84µs        ? ?/sec
smol-songs.csv: asc/thelonious monk                                                                      1.15      4.0±0.02ms        ? ?/sec    1.00      3.5±0.02ms        ? ?/sec
smol-songs.csv: basic filter: <=/Notstandskomitee                                                        2.01   298.6±16.12µs        ? ?/sec    1.00   148.5±11.89µs        ? ?/sec
smol-songs.csv: basic filter: <=/charles                                                                 3.97    193.7±1.28µs        ? ?/sec    1.00     48.9±0.46µs        ? ?/sec
smol-songs.csv: basic filter: <=/charles mingus                                                          5.76    604.8±6.50µs        ? ?/sec    1.00    105.0±0.85µs        ? ?/sec
smol-songs.csv: basic filter: <=/david                                                                   4.49    185.3±1.67µs        ? ?/sec    1.00     41.2±0.61µs        ? ?/sec
smol-songs.csv: basic filter: <=/david bowie                                                             6.78    579.2±6.94µs        ? ?/sec    1.00     85.4±0.99µs        ? ?/sec
smol-songs.csv: basic filter: <=/john                                                                    5.28    180.4±2.24µs        ? ?/sec    1.00     34.2±0.26µs        ? ?/sec
smol-songs.csv: basic filter: <=/marcus miller                                                           6.26    601.8±6.72µs        ? ?/sec    1.00     96.1±0.70µs        ? ?/sec
smol-songs.csv: basic filter: <=/michael jackson                                                         5.48    615.3±4.05µs        ? ?/sec    1.00    112.3±0.96µs        ? ?/sec
smol-songs.csv: basic filter: <=/tamo                                                                    5.26    180.7±1.13µs        ? ?/sec    1.00     34.4±0.43µs        ? ?/sec
smol-songs.csv: basic filter: <=/thelonious monk                                                         3.99    630.8±5.85µs        ? ?/sec    1.00    158.0±1.40µs        ? ?/sec
smol-songs.csv: basic filter: TO/Notstandskomitee                                                        2.09   294.8±14.58µs        ? ?/sec    1.00    140.9±0.96µs        ? ?/sec
smol-songs.csv: basic filter: TO/charles                                                                 3.92    192.8±2.70µs        ? ?/sec    1.00     49.2±0.39µs        ? ?/sec
smol-songs.csv: basic filter: TO/charles mingus                                                          5.72    610.2±4.74µs        ? ?/sec    1.00    106.6±1.24µs        ? ?/sec
smol-songs.csv: basic filter: TO/david                                                                   4.49    189.5±1.35µs        ? ?/sec    1.00     42.2±0.41µs        ? ?/sec
smol-songs.csv: basic filter: TO/david bowie                                                             6.69    581.2±5.23µs        ? ?/sec    1.00     86.9±0.65µs        ? ?/sec
smol-songs.csv: basic filter: TO/john                                                                    5.15    182.6±1.73µs        ? ?/sec    1.00     35.5±0.39µs        ? ?/sec
smol-songs.csv: basic filter: TO/marcus miller                                                           6.14    590.3±7.96µs        ? ?/sec    1.00     96.1±0.93µs        ? ?/sec
smol-songs.csv: basic filter: TO/michael jackson                                                         5.33    600.4±4.35µs        ? ?/sec    1.00    112.5±0.96µs        ? ?/sec
smol-songs.csv: basic filter: TO/tamo                                                                    5.23    181.9±1.46µs        ? ?/sec    1.00     34.8±0.53µs        ? ?/sec
smol-songs.csv: basic filter: TO/thelonious monk                                                         4.30    641.0±8.20µs        ? ?/sec    1.00    149.2±6.64µs        ? ?/sec
smol-songs.csv: basic placeholder/                                                                       1.04     61.4±0.32µs        ? ?/sec    1.00     59.2±0.47µs        ? ?/sec
smol-songs.csv: basic with quote/"Notstandskomitee"                                                      1.00    204.0±1.54µs        ? ?/sec    1.02    208.7±1.45µs        ? ?/sec
smol-songs.csv: basic with quote/"charles"                       [...]

2022-05-30 08:20 UTC, Kerollmops approved these changes
Thank you very much! Perfs are _kind of_ back!
bors merge

2022-05-30 08:36 UTC, merged