Speed up debug builds
meilisearch/milli pull request #604
Opened 2022-08-11 15:58 UTC by loiclec

Note: this draft PR is based on https://github.com/meilisearch/milli/pull/601 , for no particular reason.

## What does this PR do?
Make a series of changes with the goal of speeding up debug builds:

1. Add an `all_languages` feature which compiles charabia with its `default` features activated.
The `all_languages` feature is activated by default. But running:
```
cargo build --no-default-features
```
on `milli` is now much faster.

2. Reduce the debug optimisation level from 3 to 1

3.  Compile the build dependencies quicker as well. Previously, all build dependencies were compiled with `opt-level = 3`. Now, only the critical build dependencies are compiled with optimisations.

4. Reduce the amount of code generated by the `documents!` macro

5. Make the "progress update" closure provided to indexing functions a trait object instead of a generic parameter. This avoids monomorphising the indexing code multiple times needlessly.

## Results
Initial build times on my computer before and after these changes:
|        | cargo check | cargo check --no-default-features | cargo test | cargo test --lib | cargo test --no-default-features | cargo test --lib --no-default-features |
|--------|-------------|-----------------------------------|------------|------------------|----------------------------------|----------------------------------------|
| before | 1m05s       | 1m05s                             | 2m06s      | 1m47s            | 2m06                             | 1m47s                                  |
| after  | 28.9s       | 13.1s                             | 1m18s      | 1m08s            | 50s                              | 37.8s                                  |

2022-08-17 08:33 UTC, Kerollmops requested changes

2022-08-17 08:33 UTC, Kerollmops commented on benchmarks/Cargo.toml
> +all_languages = ["milli/default"]
```suggestion
default = ["all-languages"]
all-languages = ["milli/default"]
```

2022-08-17 08:33 UTC, Kerollmops commented on benchmarks/Cargo.toml
> +
```suggestion
```

2022-08-17 08:33 UTC, Kerollmops commented on cli/Cargo.toml
> +all_languages = ["milli/default"]
```suggestion
default = ["all-languages"]
all-languages = ["milli/default"]
```

2022-08-17 08:33 UTC, Kerollmops commented on helpers/Cargo.toml
> +all_languages = ["milli/default"]
```suggestion
[features]
default = ["all-languages"]
all-languages = ["milli/default"]
```

2022-08-17 08:33 UTC, Kerollmops commented on http-ui/Cargo.toml
> +all_languages = ["milli/default"]
```suggestion
[features]
default = ["all-languages"]
all-languages = ["milli/default"]
```

2022-08-17 08:33 UTC, Kerollmops commented on infos/Cargo.toml
> +all_languages = ["milli/default"]
```suggestion
[features]
default = ["all-languages"]
all-languages = ["milli/default"]
```

2022-08-17 08:33 UTC, Kerollmops commented on milli/Cargo.toml
> +all_languages = ["charabia/default"]
```suggestion
default = ["all-languages"]
all-languages = ["charabia/default"]
```

2022-08-17 08:33 UTC, Kerollmops commented on milli/src/update/settings.rs
> +        progress_callback: &'a (dyn Fn(UpdateIndexingStep) + Sync),
Are you sure doing that speeds up the compilation time?

2022-08-17 09:10 UTC, irevoire submitted a review, later dismissed
thanks

2022-08-17 09:25 UTC, Kerollmops approved these changes
Thank you very much!
bors merge

2022-08-17 09:59 UTC, ManyTheFish commented
lets retry,
bors merge

2022-08-17 12:06 UTC, Kerollmops commented
This is an issue with Cargo and the crates index.
bors merge

2022-08-17 12:32 UTC, loiclec commented
I rebased it on top of main, let's try again haha

bors merge

2022-08-17 12:33 UTC, Kerollmops submitted a review, later dismissed

2022-08-17 14:08 UTC, Kerollmops commented
Nice!

```
LLVM ERROR: IO failure on output stream: no space on device
error: could not compile `lindera-ipadic`
```

bors merge

2022-08-17 14:21 UTC, loiclec commented
haha! @irevoire it's your turn to try afterwards!

2022-08-17 14:48 UTC, Kerollmops commented
@loiclec Is this PR making the library bigger or what? 😂

2022-08-17 14:49 UTC, loiclec commented
I was starting to wonder as well. Since it is compiled with `opt-level = 0`, the binary will be bigger indeed :/ I'll check on my computer if it seems excessive or not.

2022-08-18 10:39 UTC, loiclec commented
On my computer (macOS, so not necessarily the same), there doesn't seem to be any significant difference between the size of the `target/` folder before and after the PR. So I am still confused as to why it fails :(
Let's hope the CI was just having a bad day?

bors merge pretty please 🥺🙏

2022-08-18 11:06 UTC, irevoire submitted a review, later dismissed
bors merge

2022-08-18 11:26 UTC, loiclec commented
nooooo 😭 I guess there really is something about that PR that makes rustc on Windows sad

2022-08-18 11:29 UTC, irevoire commented
but it worked here 🤔 
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/7032172/185384428-13ac5624-3275-4c4a-ad0a-051b1a1faf78.png">

2022-10-12 07:27 UTC, loiclec commented
I've rebased the branch on main so it's ready to merge again :-)

2022-10-12 08:54 UTC, Kerollmops approved these changes
Thank you very much.
bors merge

2022-10-12 08:54 UTC, Kerollmops commented on Cargo.toml
> +opt-level = 0
```suggestion
opt-level = 0
```

2022-10-12 09:20 UTC, ManyTheFish commented
Hey @loiclec, could it be possible to opt-in to the default features of Charabia when it is compiled in debug?
Most of the time, we don't need to have full language support activated during the development phase.

2022-10-12 09:23 UTC, merged