Fix ShellCheck errors
meilisearch/milli pull request #687
Opened 2022-11-03 17:39 UTC by azzamsa

# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-11-07 09:38 UTC, curquiza reviewed
Thanks for the PR, i'm ok with it, I just have a doubt here 👇

2022-11-07 09:38 UTC, curquiza commented on benchmarks/scripts/compare.sh
> -path_list=$(echo " $@" | sed 's/ / \/tmp\//g')
Is it what we want @irevoire?

2022-11-08 00:08 UTC, irevoire requested changes
Hey, I don’t really know which part did that. But the compare script doesn’t work with your PR

2022-11-16 16:12 UTC, curquiza commented
Closing this due to lack of answer

2022-11-16 16:12 UTC, closed without merging