Replace deprecated gh actions
meilisearch/milli pull request #711
Opened 2022-11-28 14:44 UTC by pnhatminh

# Pull Request

## Related issue
Fixes #678

## What does this PR do?
- Replace deprecated github action command with newly defined command.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-11-28 14:58 UTC, curquiza requested changes
Hello!

Thanks for your PR @pnhatminh 

Sorry I realized I read your commit too quickly commit

You should redirect to `GITHUB_OUTPUT`, cf [the article](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) I added in [the issue](https://github.com/meilisearch/milli/issues/678) 😊

2022-11-28 17:28 UTC, pnhatminh commented
> 
At the first glance, I thought that I could define the env variable as one desired. So it should be $GITHUB_OUTPUT for every env variables that I would use in the following up command, am I right?

2022-11-28 17:36 UTC, pnhatminh commented
@curquiza I added a sample code [here](https://gyazo.com/012f3922677a47d88e76dcaae951c25a) for clarification

2022-11-29 09:56 UTC, curquiza approved these changes
Thanks @pnhatminh 

bors merge

2022-11-29 10:27 UTC, merged